"""equal_weight strategy — generated by autobacktest init-strategy."""

from typing import Any

import pandas as pd


def generate_signals(prices: pd.DataFrame, config: dict[str, Any]) -> pd.DataFrame:
    """Generate portfolio allocation weights.

    Args:
        prices: Daily close prices DataFrame (DatetimeIndex).
        config: Strategy configuration dictionary.

    Returns:
        pd.DataFrame: Weights DataFrame indexed by rebalance dates.
    """
    universe = config.get("universe", [])
    cash_asset = config.get("params", {}).get("cash_asset", "BIL")

    if prices.empty:
        return pd.DataFrame(0.0, index=pd.DatetimeIndex([]), columns=prices.columns)

    available = set(prices.columns)
    if cash_asset not in available:
        raise ValueError(f"Cash asset {cash_asset} not in price data")

    start = prices.index.min()
    end = prices.index.max()
    rebalance_dates = pd.date_range(start=start, end=end, freq="BME", tz=prices.index.tz).intersection(prices.index)
    weights = pd.DataFrame(0.0, index=rebalance_dates, columns=prices.columns)

    for date in rebalance_dates:
        valid_assets = [t for t in universe if t in available]
        if valid_assets:
            w = 1.0 / len(valid_assets)
            for asset in valid_assets:
                weights.loc[date, asset] = w

    return weights
