"""momentum_rotation strategy — generated by autobacktest init-strategy."""

from typing import Any

import pandas as pd


def generate_signals(prices: pd.DataFrame, config: dict[str, Any]) -> pd.DataFrame:
    """Generate momentum rotation signals.

    Ranks assets by trailing return over the momentum lookback period,
    selects the top N, and allocates equally.  If no assets have positive
    momentum the full allocation goes to the cash asset.

    Args:
        prices: Daily close prices DataFrame (DatetimeIndex).
        config: Strategy configuration dictionary.

    Returns:
        pd.DataFrame: Weights DataFrame indexed by rebalance dates.
    """
    cash_asset = config.get("params", {}).get("cash_asset", "BIL")
    lookback = config.get("momentum_lookback", 12)
    top_n = config.get("params", {}).get("top_n", 3)

    if prices.empty:
        return pd.DataFrame(0.0, index=pd.DatetimeIndex([]), columns=prices.columns)

    available = set(prices.columns)
    if cash_asset not in available:
        raise ValueError(f"Cash asset {cash_asset} not in price data")

    start = prices.index.min()
    end = prices.index.max()
    rebalance_dates = pd.date_range(start=start, end=end, freq="BME", tz=prices.index.tz).intersection(prices.index)
    weights = pd.DataFrame(0.0, index=rebalance_dates, columns=prices.columns)

    trading_days = lookback * 21

    for date in rebalance_dates:
        hist = prices.loc[:date]
        if len(hist) < trading_days + 1:
            continue

        returns = hist.pct_change(trading_days).iloc[-1]
        ranked = returns.dropna().sort_values(ascending=False)
        selected = [t for t in ranked.index if t in available and t != cash_asset][:top_n]

        if not selected:
            weights.loc[date, cash_asset] = 1.0
        else:
            w = 1.0 / len(selected)
            for asset in selected:
                weights.loc[date, asset] = w

    return weights
