"""Strategy template registry and renderers.

Templates are stored as inline string constants rather than external files,
so they work regardless of installation method (editable, non-editable,
platform, Python version).
"""

from __future__ import annotations

TEMPLATE_REGISTRY: dict[str, str] = {
    "equal-weight": "equal_weight",
    "momentum-rotation": "momentum_rotation",
}


STRATEGY_TEMPLATES: dict[str, str] = {
    "equal_weight": '''"""__NAME__ strategy — generated by autobacktest init-strategy."""

from typing import Any

import pandas as pd


def generate_signals(prices: pd.DataFrame, config: dict[str, Any]) -> pd.DataFrame:
    """Generate portfolio allocation weights.

    Args:
        prices: Daily close prices DataFrame (DatetimeIndex).
        config: Strategy configuration dictionary.

    Returns:
        pd.DataFrame: Weights DataFrame indexed by rebalance dates.
    """
    universe = config.get("universe", [])
    cash_asset = config.get("params", {}).get("cash_asset", "BIL")

    if prices.empty:
        return pd.DataFrame(0.0, index=pd.DatetimeIndex([]), columns=prices.columns)

    available = set(prices.columns)
    if cash_asset not in available:
        raise ValueError(f"Cash asset {cash_asset} not in price data")

    start = prices.index.min()
    end = prices.index.max()
    rebalance_dates = pd.date_range(start=start, end=end, freq="BME", tz=prices.index.tz).intersection(prices.index)
    weights = pd.DataFrame(0.0, index=rebalance_dates, columns=prices.columns)

    for date in rebalance_dates:
        valid_assets = [t for t in universe if t in available]
        if valid_assets:
            w = 1.0 / len(valid_assets)
            for asset in valid_assets:
                weights.loc[date, asset] = w

    return weights
''',
    "momentum_rotation": '''"""__NAME__ strategy — generated by autobacktest init-strategy."""

from typing import Any

import pandas as pd


def generate_signals(prices: pd.DataFrame, config: dict[str, Any]) -> pd.DataFrame:
    """Generate momentum rotation signals.

    Ranks assets by trailing return over the momentum lookback period,
    selects the top N, and allocates equally.  If no assets have positive
    momentum the full allocation goes to the cash asset.

    Args:
        prices: Daily close prices DataFrame (DatetimeIndex).
        config: Strategy configuration dictionary.

    Returns:
        pd.DataFrame: Weights DataFrame indexed by rebalance dates.
    """
    cash_asset = config.get("params", {}).get("cash_asset", "BIL")
    lookback = config.get("momentum_lookback", 12)
    top_n = config.get("params", {}).get("top_n", 3)

    if prices.empty:
        return pd.DataFrame(0.0, index=pd.DatetimeIndex([]), columns=prices.columns)

    available = set(prices.columns)
    if cash_asset not in available:
        raise ValueError(f"Cash asset {cash_asset} not in price data")

    start = prices.index.min()
    end = prices.index.max()
    rebalance_dates = pd.date_range(start=start, end=end, freq="BME", tz=prices.index.tz).intersection(prices.index)
    weights = pd.DataFrame(0.0, index=rebalance_dates, columns=prices.columns)

    trading_days = lookback * 21

    for date in rebalance_dates:
        hist = prices.loc[:date]
        if len(hist) < trading_days + 1:
            continue

        returns = hist.pct_change(trading_days).iloc[-1]
        ranked = returns.dropna().sort_values(ascending=False)
        selected = [t for t in ranked.index if t in available and t != cash_asset and ranked[t] > 0][:top_n]

        if not selected:
            weights.loc[date, cash_asset] = 1.0
        else:
            w = 1.0 / len(selected)
            for asset in selected:
                weights.loc[date, asset] = w

    return weights
''',
}


PROGRAM_TEMPLATE = """# Objective

Optimize the **__NAME__** strategy (__UNIVERSE__ universe, benchmark: __BENCHMARK__).

Describe your specific targets here — the LLM optimizer uses this as its north star.

Examples:
- "Increase Sharpe ratio above 1.2 while keeping drawdown below __DRAWDOWN_PCT__%"
- "Improve risk-adjusted returns; reduce turnover below __TURNOVER__"
- "Maintain CAGR above 10% with max drawdown under __DRAWDOWN_PCT__%"

# Constraints

- Maximum drawdown in the holdout period must not exceed __DRAWDOWN_PCT__%.
- Annualized portfolio turnover must remain below __TURNOVER__.
- The strategy must pass all regime stress tests (2008 GFC, 2020 COVID, 2022 bear market).
- Monthly rebalancing on the last trading day must be preserved (momentum lookback: __LOOKBACK__ months).
- Only ``pandas`` and ``numpy`` imports are permitted in the strategy code.
- The ``generate_signals(prices: pd.DataFrame, config: dict) -> pd.DataFrame`` signature must be preserved.

## Strategy Details

Optional: Add background, references, or design notes here.

**Asset universe:** __UNIVERSE__
**Benchmark:** __BENCHMARK__

---

**Tip:** Run ``uv run autobacktest run --program program-__NAME__.md`` to start optimizing.
"""


def _lookup(template_name: str) -> str:
    """Resolve a template name to its strategy stem, or raise."""
    stem = TEMPLATE_REGISTRY.get(template_name)
    if stem is None:
        valid = ", ".join(sorted(TEMPLATE_REGISTRY))
        raise ValueError(f"Unknown template '{template_name}'. Valid options: {valid}")
    return stem


def _substitute(text: str, subs: dict[str, str]) -> str:
    """Replace all sentinel keys in *text* with their values."""
    for key, val in subs.items():
        text = text.replace(key, val)
    return text


def render_strategy_source(
    strategy_name: str,
    cash_asset: str,
    template_name: str,
) -> str:
    """Load and render a strategy ``.py`` template.

    Replaces the template's hardcoded name in the docstring with
    *strategy_name*, and its ``"BIL"`` default with *cash_asset* when
    *cash_asset* differs from ``"BIL"``.
    """
    stem = _lookup(template_name)
    source = STRATEGY_TEMPLATES[stem]
    source = source.replace("__NAME__", strategy_name, 1)
    if cash_asset != "BIL":
        source = source.replace('"BIL"', f'"{cash_asset}"')
    return source


def render_program_template(
    _template_name: str,
    strategy_name: str,
    universe_str: str,
    benchmark: str,
    mdd: float,
    turnover: float,
    lookback: int,
) -> str:
    """Load and render a program ``.md`` template.

    Substitutes all sentinel values into the template.
    """
    subs: dict[str, str] = {
        "__NAME__": strategy_name,
        "__UNIVERSE__": universe_str,
        "__BENCHMARK__": benchmark,
        "__DRAWDOWN_PCT__": str(round(mdd * 100)),
        "__TURNOVER__": str(turnover),
        "__LOOKBACK__": str(lookback),
    }
    return _substitute(PROGRAM_TEMPLATE, subs)
